### ISSUE TITLE
Possibly need to deprecate in favor of facebook package `react-is`

### ISSUE THREAD

**Issue by JackHowa** [treyhuffine/is-react#44]
Sorry to bother but I was looking at this again and noticed an update to this thread. Curious what you think @treyhuffine about deprecating this for react.memo support and other concerns as it seems facebook has official support for this. 

https://www.npmjs.com/package/react-is 
https://stackoverflow.com/questions/33199959/how-to-detect-a-react-component-vs-a-react-element/62663794#62663794

**Comment by treyhuffine** [comment]
Great feedback @JackHowa. I've added a note to the README about `react-is` so devs will be sure to see it and can determine the best package to use for their needs.
